<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class UserSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'nim' => '2024001',
                'nama_lengkap' => 'Ahmad Rizki',
                'email' => 'ahmad.rizki@politala.ac.id',
                'password' => password_hash('password123', PASSWORD_DEFAULT),
                'no_wa' => '081234567890',
                'no_hp' => '081234567890',
                'tempat_lahir' => 'Pelaihari',
                'tanggal_lahir' => '2000-05-15',
                'tempat_tinggal' => 'Jl. A. Yani Km.6, Pelaihari, Tanah Laut',
                'program_studi' => 'Teknologi Informasi',
                'agama' => 'Islam',
                'penyakit' => 'Tidak ada',
                'pengalaman_organisasi' => 'OSIS SMA, Rohis',
                'alasan_mapala' => 'Ingin mengembangkan kemampuan outdoor dan mencintai alam',
                'foto' => 'ahmad-rizki.jpg',
                'role' => 'admin',
                'status' => 'approved',
                'angkatan' => 2024,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nim' => '2024002',
                'nama_lengkap' => 'Siti Nurhaliza',
                'email' => 'siti.nurhaliza@politala.ac.id',
                'password' => password_hash('password123', PASSWORD_DEFAULT),
                'no_wa' => '081234567891',
                'no_hp' => '081234567891',
                'tempat_lahir' => 'Banjarmasin',
                'tanggal_lahir' => '2001-08-20',
                'tempat_tinggal' => 'Jl. A. Yani Km.6, Pelaihari, Tanah Laut',
                'program_studi' => 'Akuntansi',
                'agama' => 'Islam',
                'penyakit' => 'Tidak ada',
                'pengalaman_organisasi' => 'Pramuka, PMR',
                'alasan_mapala' => 'Tertarik dengan kegiatan rock climbing dan ingin mengembangkan skill',
                'foto' => 'siti-nurhaliza.jpg',
                'role' => 'anggota',
                'status' => 'approved',
                'angkatan' => 2024,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nim' => '2024003',
                'nama_lengkap' => 'Muhammad Fadli',
                'email' => 'muhammad.fadli@politala.ac.id',
                'password' => password_hash('password123', PASSWORD_DEFAULT),
                'no_wa' => '081234567892',
                'no_hp' => '081234567892',
                'tempat_lahir' => 'Martapura',
                'tanggal_lahir' => '2000-12-10',
                'tempat_tinggal' => 'Jl. A. Yani Km.6, Pelaihari, Tanah Laut',
                'program_studi' => 'Teknologi Otomotif',
                'agama' => 'Islam',
                'penyakit' => 'Tidak ada',
                'pengalaman_organisasi' => 'Karang Taruna',
                'alasan_mapala' => 'Suka dengan kegiatan air dan ingin belajar arung jeram',
                'foto' => 'muhammad-fadli.jpg',
                'role' => 'anggota',
                'status' => 'approved',
                'angkatan' => 2024,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nim' => '2024004',
                'nama_lengkap' => 'Dewi Sartika',
                'email' => 'dewi.sartika@politala.ac.id',
                'password' => password_hash('password123', PASSWORD_DEFAULT),
                'no_wa' => '081234567893',
                'no_hp' => '081234567893',
                'tempat_lahir' => 'Banjarbaru',
                'tanggal_lahir' => '2001-03-25',
                'tempat_tinggal' => 'Jl. A. Yani Km.6, Pelaihari, Tanah Laut',
                'program_studi' => 'Agroindustri',
                'agama' => 'Islam',
                'penyakit' => 'Tidak ada',
                'pengalaman_organisasi' => 'KPA, Mapala SMA',
                'alasan_mapala' => 'Ingin berkontribusi dalam penelitian lingkungan dan konservasi',
                'foto' => 'dewi-sartika.jpg',
                'role' => 'anggota',
                'status' => 'approved',
                'angkatan' => 2024,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'nim' => '2024005',
                'nama_lengkap' => 'Rizki Pratama',
                'email' => 'rizki.pratama@politala.ac.id',
                'password' => password_hash('password123', PASSWORD_DEFAULT),
                'no_wa' => '081234567894',
                'no_hp' => '081234567894',
                'tempat_lahir' => 'Tanjung',
                'tanggal_lahir' => '2000-07-08',
                'tempat_tinggal' => 'Jl. A. Yani Km.6, Pelaihari, Tanah Laut',
                'program_studi' => 'TPT',
                'agama' => 'Islam',
                'penyakit' => 'Tidak ada',
                'pengalaman_organisasi' => 'PMR, SAR',
                'alasan_mapala' => 'Ingin mengembangkan kemampuan SAR dan membantu sesama',
                'foto' => 'rizki-pratama.jpg',
                'role' => 'anggota',
                'status' => 'approved',
                'angkatan' => 2024,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        $this->db->table('users')->insertBatch($data);
    }
}